### ISSUE TITLE
Second start of the instance result in partly missing sounds

### ISSUE THREAD

**Issue by egut** [Allexio/Cinnamon#2]
I was playing around with 1.0.1 of the pack and noticed that normal step sound disappeared the second time I started the instance.

**How to reproduce**

1. Download a new instance of Allexio Create modpack 
2. Start it and create a New world
3. Move around an you should hear steps.
4. Stop the instance
5. Start the same instance and same world
6. Now no step sounds, but break block sound are still there.

**Log output**

In the first log there are creation of missing config-files. (possible reason for missing sound is that the default value in package is not the same as default value in config file?)

In the second log file there are hundreds of these errors: 
```
[16:12:39] [Worker-Main-3/ERROR]:
 Failed to modify baked model after bake
java.lang.IllegalArgumentException: Cannot create a MultiRenderTypeModel for a wrapped model that isn't CompositeModel.Baked
	at com.simibubi.create.foundation.render.MultiRenderTypeModel$Builder.build(MultiRenderTypeModel.java:125) ~[create-sodium-fix-0.5.1-d-build.5+mc1.20.1.jar:?]
	at com.simibubi.create.foundation.render.MultiRenderTypeModel.forNixieTube(MultiRenderTypeModel.java:65) ~[create-sodium-fix-0.5.1-d-build.5+mc1.20.1.jar:?]
	at com.simibubi.create.foundation.utility.ModelSwapper.modifyModelAfterBake(ModelSwapper.java:52) ~[create-sodium-fix-0.5.1-d-build.5+mc1.20.1.jar:?]
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoaderPluginContextImpl.lambda$new$6(ModelLoaderPluginContextImpl.java:97) ~[fabric-model-loading-api-v1-1.0.+709a987177-dc8a0728ca367bb2.jar:?]
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.modifyModelAfterBake(ModelLoadingEventDispatcher.java:291) ~[fabric-model-loading-api-v1-1.0.+709a987177-dc8a0728ca367bb2.jar:?]
	at net.minecraft.class_1088$class_7778.redirect$cdo000$fabric-model-loading-api-v1$invokeModifyAfterBake(class_1088.java:560) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:426) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.method_45877(class_1088.java:188) ~[client-intermediary.jar:?]
	at java.util.HashMap$KeySet.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_1088.method_45876(class_1088.java:185) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45883(class_1092.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45885(class_1092.java:92) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
```
also the second logfile clam to miss some additional sound events, not present in the first log file.

**Comment by Allexio** [comment]
This is very odd, as I've faced no such problems.
Do you mean this happens for all clients when the server is restarted?
Or it happens for clients who restart their game?

**Comment by Allexio** [comment]
(Also, it's normal that it creates the missing config files, my modpack only includes the config files that I have actually modified - if I leave the default settings, then I don't include the modfile)

**Comment by egut** [comment]
I have not tested with a real server yet, only in standalone mode so far. 

I tried see if I could pinpoint it better by starting from 0.9.16 and add the mods listed for 1.0.0 one by one. No major issue. Then I toke the config from 1.0.0 (clean download) and just coped over. Then I got 100th of the error above and the same list of missing "sound events" but for some reason the steps worked. (The missing sound events didn't obviously )

This always may it trickier but the configs order might have an impact. I looked for the issue on missing sound events and there might be a json file that have a list (or object) that ends with  , (comma) that confuses java. 

[1, 2, 3, ] <-- not working
[1, 2, 3 ] <-- working

**Comment by egut** [comment]
For the "Failed to modify baked model after bake" errors I didn't find any good explanations, if you do please point them to me.

**Comment by Allexio** [comment]
For the model bake errors, I'd ignore this for now. The pack uses a temporary solution to workaround the issues between Create & latest iris/sodium/indium.
As soon as Create releases their update to fix this issue, I'll move ot that and then I can get official support from them.
The sound issue _is_ really odd, though.
I'll check the config files.

**Comment by Allexio** [comment]
I cannot reproduce this bug...
Are you sure you didn't modify any of the config files?
Did you have the time to try on a proper server?

**Comment by egut** [comment]
## Sorry for slow to answer, I did several fresh install
0.9.7 works fine both first and second run.

## 1.0.1 don't

### Fresh install 1.0.1 connect with servers 1.0.1 fresh install:

First run for client [2023-11-29-1.log.gz](https://github.com/Allexio/create-plus/files/13505248/2023-11-29-1.log.gz) step sound works.
Second run for client [latest.log](https://github.com/Allexio/create-plus/files/13505249/latest.log) step sound don't work


### Fresh install 1.0.1 singleplayer startup: 

First run [2023-11-29-1.log.gz](https://github.com/Allexio/create-plus/files/13505260/2023-11-29-1.log.gz) step sound works.
Second run [2023-11-29-2.log.gz](https://github.com/Allexio/create-plus/files/13505261/2023-11-29-2.log.gz) step sound don't work

**Comment by Allexio** [comment]
Okay I found the issue.
Turns out that for some reason on the second run it disables the associated resource pack.
I'll see about updating the options.txt

**Comment by egut** [comment]
Great! 

What option is disabled? so I can learn something new.

**Comment by Allexio** [comment]
Uploaded version 1.0.2 on Modrinth, can you please check that it fixes the issue for you?

**Comment by Allexio** [comment]
To answer your question: The presence footsteps resource pack itself is what was disabled.
I added it in the enabled resource packs in the `options.txt` file.
The resource pack line in the `options.txt` file now reads:
`resourcePacks:["fabric","minecraft:supporteatinganimation", "presencefootsteps:default_sound_pack"]`

**Comment by egut** [comment]
In 1.0.2 the foot step sounds work very fine! Good work,  thanks! 

I do see a about 20 or so  `Sound event naturalist:entity.bear.death not found` for different sounds but when killing a bear it do give a sound, so its a but unclear it something gets confused or not. Note I only see this in the second run log not the first.

**Comment by Allexio** [comment]
Yes I know about the sound event missing issues and I've reported it to the
mod author but for now no response. But that's another issue. I'll close
this issue.
